/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 chair.gltf --transform
Author: woziu (https://sketchfab.com/woziu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/first-model-smart-crop-5619099eeb6b4b838e2dba0cc990da04
Title: First model + smart crop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -11.33, 11.33]} rotation={[-Math.PI, 0, 0]}>
        <group position={[-15.44, -20.77, -15.23]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Material_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chair-transformed.glb')
